/**
 * Oyun metinleri. TASLAK: sahibinin onayını bekliyor (spec §19, karar 4). Ürün adları
 * menüden, gece cümleleri ana sayfadan okunur; burada tekrar yazılmaz.
 */
export const oyun = {
  baslik: 'Sofra Yetiştir',
  oyna: 'Oyna',
  tekrar: 'Tekrar Oyna',
  duraklat: 'Duraklat',
  devam: 'Devam Et',
  cik: 'Oyundan Çık',
  ses: 'Ses',
  saat: 'Saat',
  puan: 'Puan',
  kombo: 'Kombo',
  kapida: 'Kapıda',
  ocak: 'Ocak',
  tezgah: 'Tezgah',
  raf: 'Raf',
  sofra: 'Sofra',
  bosSofra: 'Boş sofra',
  kurulu: 'kurulu',
  ucSofraKalkti: 'üç sofra kalktı',
  /** Canlı bölge (spec §15): önemli anlar, saniyede en çok bir. `{puan}` ödemeyle değişir. */
  duyuru: {
    sonSaat: 'Son saat',
    porsiyon: 'Bir porsiyon',
    sofraKalkti: 'Sofra kalktı',
    fisTamam: 'Fiş tamam, +{puan}',
    sisYandi: 'Şiş yandı',
    sogudu: 'Şiş soğudu',
  },
  ozet: { sofra: 'sofra', sis: 'şiş', tamKivam: 'tam kıvam', enUzunKombo: 'en uzun kombo' },
  enIyi: 'En iyin',
  yeniEnIyi: 'Yeni en iyi',
  kaldi: 'kaldı',
  /** Sıralama ve katılım (spec §7, §8, §11). Katılım cümlesi Md. 11(2)(A) onayının metnidir. */
  siralamayaYaz: 'Bu Skoru Sıralamaya Yaz',
  siralama: {
    baslik: 'Sıralama',
    haftaninIlkUcu: 'Haftanın ilk üçü',
    buHafta: 'Bu hafta',
    tumZamanlar: 'Tüm zamanlar',
    sonSampiyon: 'Son şampiyon',
    sira: 'Sıran: {sira}',
    ustekiFark: 'bir üsttekine {fark} kaldı',
    sifirlanma: 'Sıfırlanır: {zaman}',
    bos: 'Bu hafta henüz skor yok.',
    gizliAd: 'Gizli',
    alinamadi: 'Sıralama şu an alınamıyor.',
    oyunaDon: 'Oyuna Dön',
  },
  katilim: {
    baslik: 'Sıralamaya katıl',
    takmaAd: 'Takma ad',
    kural: '3-12 karakter: harf, rakam, boşluk, nokta, alt çizgi, tire.',
    aciklama:
      "Takma adın ve turların Türkiye'deki sunucumuzda tutulur; takma adın herkese açık sıralamada görünür.",
    uyari: 'Hesap bu tarayıcıya bağlıdır: tarayıcı verisi silinirse hesap ve ödül kodu kaybolur.',
    kaydet: 'Kaydet ve Katıl',
    vazgec: 'Vazgeç',
    red: 'Bu takma ad kullanılamaz.',
    hata: 'Kayıt yapılamadı, tekrar dene.',
  },
  gonderim: {
    cevrimdisi: 'Çevrimdışı tur: sıralamaya girmez.',
    gonderiliyor: 'Sıralamaya yazılıyor',
    hata: 'Sıralamaya yazılamadı.',
    tekrarDene: 'Tekrar Dene',
    sira: 'Haftalık sıra: {sira}',
    enIyin: 'Haftalık en iyin: {puan}',
  },
  hesap: {
    hesabin: 'Hesabın: {ad}',
    sil: 'Hesabımı Sil',
    silSoru: 'Hesap, turlar ve ödül kodu silinir.',
    silOnay: 'Evet, Sil',
    silindi: 'Hesap silindi.',
    silinemedi: 'Silinemedi, tekrar dene.',
  },
  odul: {
    baslik: 'Ödül kodun',
    sira: 'Haftanın {sira}. sırası',
    gecerlilik: 'Son gün: {tarih}',
    ekranGoruntusu: 'Ekran görüntüsünü al; kodu sofrada göster.',
    kullanildi: 'Kullanıldı',
  },
}
