/**
 * Oyun metinleri. TASLAK: sahibinin onayını bekliyor (spec §19, karar 4). Ürün adları
 * menüden, gece cümleleri ana sayfadan okunur; burada tekrar yazılmaz.
 */
export const oyun = {
  baslik: 'Sofra Yetiştir',
  oyna: 'Oyna',
  tekrar: 'Tekrar Oyna',
  duraklat: 'Duraklat',
  devam: 'Devam Et',
  cik: 'Oyundan Çık',
  ses: 'Ses',
  saat: 'Saat',
  puan: 'Puan',
  kombo: 'Kombo',
  kapida: 'Kapıda',
  ocak: 'Ocak',
  raf: 'Raf',
  tabak: 'Tabak',
  kase: 'Kase',
  cop: 'Çöp',
  misafir: 'Misafir',
  bosYer: 'boş yer',
  bahsis: 'Bahşiş',
  /** Düğme adlarının durum parçaları (spec tabak §3): "Ocak 1: ciğer, hazır", "Misafir 2: ciğer ve domates istiyor, sabır yüzde 60". */
  durum: {
    pisiyor: 'pişiyor',
    hazir: 'hazır',
    elde: 'elde',
    bos: 'boş',
    odedi: 'ödedi',
    istiyor: '{fis} istiyor',
    sabir: 'sabır yüzde {yuzde}',
    ve: ' ve ',
  },
  ucMisafirKalkti: 'üç misafir kalktı',
  /** Canlı bölge (spec §15): önemli anlar, saniyede en çok bir. */
  duyuru: {
    sonSaat: 'Son saat',
    misafirKalkti: 'Misafir kalktı',
    teslim: 'Misafir {no} ödedi, +{puan}',
    bahsis: 'Bahşiş +{puan}',
    yanlisTabak: 'Tabak fişe uymuyor',
    sisYandi: 'Şiş yandı',
    paraSoldu: 'Bahşiş soldu',
    tabagaKondu: 'Tabağa kondu',
    elde: '{urun} elde',
  },
  ozet: { misafir: 'misafir', sis: 'şiş', tamKivam: 'tam kıvam', enUzunKombo: 'en uzun kombo', bahsis: 'bahşiş' },
  /** Rehberli ilk tur (spec tabak §7); her cümle en çok altı sözcük. */
  rehber: {
    fis: 'Misafir ciğer istiyor',
    raf: 'Ciğer şişini ocağa koy',
    pisiyor: 'Şiş pişiyor, altın olunca tut',
    hazir: 'Şişi tabağa sürükle',
    tabak: 'Şişi tabağa sürükle',
    misafir: 'Tabağı misafire götür',
    para: 'Bahşişi al',
    eslikci: 'Domatesi de tabağa koy',
    tamam: 'Tamam',
    atla: 'Atla',
  },
  enIyi: 'En iyin',
  yeniEnIyi: 'Yeni en iyi',
  kaldi: 'kaldı',
  /** Sıralama ve katılım (spec §7, §8, §11). Katılım cümlesi Md. 11(2)(A) onayının metnidir. */
  siralamayaYaz: 'Bu Skoru Sıralamaya Yaz',
  siralama: {
    baslik: 'Sıralama',
    haftaninIlkUcu: 'Haftanın ilk üçü',
    buHafta: 'Bu hafta',
    tumZamanlar: 'Tüm zamanlar',
    sonSampiyon: 'Son şampiyon',
    sira: 'Sıran: {sira}',
    ustekiFark: 'bir üsttekine {fark} kaldı',
    sifirlanma: 'Sıfırlanır: {zaman}',
    bos: 'Bu hafta henüz skor yok.',
    gizliAd: 'Gizli',
    alinamadi: 'Sıralama şu an alınamıyor.',
    oyunaDon: 'Oyuna Dön',
  },
  giris: {
    takmaAd: 'Takma adın (isteğe bağlı)',
  },
  katilim: {
    baslik: 'Sıralamaya katıl',
    takmaAd: 'Takma ad',
    kural: '3-12 karakter: harf, rakam, boşluk, nokta, alt çizgi, tire.',
    aciklama:
      "Takma adın ve turların Türkiye'deki sunucumuzda tutulur; takma adın herkese açık sıralamada görünür.",
    uyari: 'Hesap bu tarayıcıya bağlıdır: tarayıcı verisi silinirse hesap ve ödül kodu kaybolur.',
    kaydet: 'Kaydet ve Katıl',
    vazgec: 'Vazgeç',
    red: 'Bu takma ad kullanılamaz.',
    hata: 'Kayıt yapılamadı, tekrar dene.',
  },
  gonderim: {
    cevrimdisi: 'Çevrimdışı tur: sıralamaya girmez.',
    gonderiliyor: 'Sıralamaya yazılıyor',
    hata: 'Sıralamaya yazılamadı.',
    reddedildi: 'Bu tur sıralamaya yazılamaz.',
    tekrarDene: 'Tekrar Dene',
    sira: 'Sıralamaya yazıldı: sıra {sira}',
    enIyin: 'Haftalık en iyin: {puan}',
  },
  hesap: {
    hesabin: 'Hesabın: {ad}',
    sil: 'Hesabımı Sil',
    silSoru: 'Hesap, turlar ve ödül kodu silinir.',
    silOnay: 'Evet, Sil',
    silindi: 'Hesap silindi.',
    silinemedi: 'Silinemedi, tekrar dene.',
  },
  odul: {
    baslik: 'Ödül kodun',
    sira: 'Haftanın {sira}. sırası',
    gecerlilik: 'Son gün: {tarih}',
    ekranGoruntusu: 'Ekran görüntüsünü al; kodu sofrada göster.',
    kullanildi: 'Kullanıldı',
  },
}
