/** Game copy. DRAFT: awaiting the owner's approval (spec §19, decision 4). */
export const oyun = {
  baslik: 'Sofra Yetiştir',
  oyna: 'Play',
  tekrar: 'Play Again',
  duraklat: 'Pause',
  devam: 'Resume',
  cik: 'Leave Game',
  ses: 'Sound',
  saat: 'Time',
  puan: 'Score',
  kombo: 'Combo',
  kapida: 'At the door',
  ocak: 'Fire',
  raf: 'Rack',
  tabak: 'Plate',
  kase: 'Bowl',
  cop: 'Bin',
  misafir: 'Guest',
  bosYer: 'empty seat',
  bahsis: 'Tip',
  durum: {
    pisiyor: 'cooking',
    hazir: 'ready',
    elde: 'in hand',
    bos: 'empty',
    odedi: 'paid',
    istiyor: 'wants {fis}',
    sabir: 'patience {yuzde} percent',
    ve: ' and ',
  },
  ucMisafirKalkti: 'three guests walked out',
  duyuru: {
    sonSaat: 'Last hour',
    misafirKalkti: 'A guest walked out',
    teslim: 'Guest {no} paid, +{puan}',
    bahsis: 'Tip +{puan}',
    yanlisTabak: 'Plate does not match the ticket',
    sisYandi: 'Skewer burnt',
    paraSoldu: 'Tip gone',
    tabagaKondu: 'On the plate',
    elde: '{urun} in hand',
  },
  ozet: { misafir: 'guests', sis: 'skewers', tamKivam: 'just right', enUzunKombo: 'longest combo', bahsis: 'tips' },
  rehber: {
    fis: 'The guest wants liver',
    raf: 'Tap Ciğer to start grilling',
    pisiyor: 'Wait until it turns golden',
    hazir: 'Drag the skewer to the plate',
    tabak: 'Drag the skewer to the plate',
    misafir: 'Drag the plate to the guest',
    para: 'Tap the tip',
    eslikci: 'Add the tomato too',
    tamam: 'Got It',
    atla: 'Skip',
  },
  enIyi: 'Your best',
  yeniEnIyi: 'New best',
  kaldi: 'to go',
  siralamayaYaz: 'Put This Score on the Board',
  siralama: {
    baslik: 'Leaderboard',
    haftaninIlkUcu: 'Top three this week',
    buHafta: 'This week',
    tumZamanlar: 'All time',
    sonSampiyon: 'Last champion',
    sira: 'Your rank: {sira}',
    ustekiFark: '{fark} behind the one above',
    sifirlanma: 'Resets: {zaman}',
    bos: 'No scores yet this week.',
    gizliAd: 'Hidden',
    alinamadi: 'The leaderboard is not available right now.',
    oyunaDon: 'Back to the Game',
  },
  giris: {
    takmaAd: 'Nickname (optional)',
  },
  katilim: {
    baslik: 'Join the leaderboard',
    takmaAd: 'Nickname',
    kural: '3-12 characters: letters, digits, space, dot, underscore, hyphen.',
    aciklama:
      'Your nickname and rounds are stored on our server in Turkey; your nickname is shown on the public ' +
      'leaderboard.',
    uyari: 'The account is tied to this browser: if browser data is cleared, the account and the prize code are lost.',
    kaydet: 'Save and Join',
    vazgec: 'Cancel',
    red: 'This nickname cannot be used.',
    hata: 'Could not sign up, try again.',
  },
  gonderim: {
    cevrimdisi: 'Offline round: it does not count for the board.',
    gonderiliyor: 'Sending to the board',
    hata: 'Could not send to the board.',
    reddedildi: 'This round cannot go on the board.',
    tekrarDene: 'Try Again',
    sira: 'Added to the ranking: rank {sira}',
    enIyin: 'Your weekly best: {puan}',
  },
  hesap: {
    hesabin: 'Your account: {ad}',
    sil: 'Delete My Account',
    silSoru: 'The account, its rounds and the prize code are deleted.',
    silOnay: 'Yes, Delete',
    silindi: 'Account deleted.',
    silinemedi: 'Could not delete, try again.',
  },
  odul: {
    baslik: 'Your prize code',
    sira: 'Rank {sira} of the week',
    gecerlilik: 'Last day: {tarih}',
    ekranGoruntusu: 'Take a screenshot; show the code at the table.',
    kullanildi: 'Used',
  },
}
