/** Game copy. DRAFT: awaiting the owner's approval (spec §19, decision 4). */
export const oyun = {
  baslik: 'Sofra Yetiştir',
  oyna: 'Play',
  tekrar: 'Play Again',
  duraklat: 'Pause',
  devam: 'Resume',
  ses: 'Sound',
  saat: 'Time',
  puan: 'Score',
  kombo: 'Combo',
  kapida: 'At the door',
  ocak: 'Fire',
  tezgah: 'Counter',
  raf: 'Rack',
  sofra: 'Table',
  bosSofra: 'Empty table',
  kurulu: 'set',
  ucSofraKalkti: 'three tables walked out',
  duyuru: {
    sonSaat: 'Last hour',
    porsiyon: 'One portion',
    sofraKalkti: 'A table walked out',
    fisTamam: 'Ticket done, +{puan}',
    sisYandi: 'Skewer burnt',
    sogudu: 'Skewer went cold',
  },
  ozet: { sofra: 'tables', sis: 'skewers', tamKivam: 'just right', enUzunKombo: 'longest combo' },
  enIyi: 'Your best',
  yeniEnIyi: 'New best',
  kaldi: 'to go',
}
